yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path(
        'posts/<int:post_id>/deletion/',
        views.post_delete,
        name='post_delete'
    ),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        'Group',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(
        unique=True
    )
    description = models.TextField()

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created']


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )

    class Meta:
        unique_together = ('user', 'author')

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group', 'image']
        widget = {
            'text': forms.Textarea(attrs={'cols': 40, 'rows': 10})
        }
        labels = {
            'text': 'Текст поста',
            'group': 'Группа',
            'image': 'Изображение'
        }
        help_texts = {
            'text': 'Введите текст',
            'group': 'Выберите группу',
            'image': 'Выберите изображение'
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widget = {
            'text': forms.Textarea(attrs={'cols': 40, 'rows': 10})
        }
        labels = {
            'text': 'Текст комментария',
        }
        help_texts = {
            'text': 'Введите комментарий',
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth import get_user_model

from .forms import PostForm, CommentForm
from .models import Group, Post, Follow

User = get_user_model()


def index(request):
    template = 'posts/index.html'
    post_list = Post.objects.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group)
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    user = get_object_or_404(User, username=username)
    if not request.user.is_authenticated:
        following = False
    else:
        following = Follow.objects.filter(
            author=user,
            user=request.user,
        ).exists()
    post_list = user.posts.all()
    post_count = post_list.count()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'profile_user': user,
        'post_count': post_count,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, id=post_id)
    comments = post.comments.all()
    post_count = post.author.posts.all().count()
    form = CommentForm(request.POST or None)
    context = {
        'post': post,
        'post_count': post_count,
        'form': form,
        'comments': comments
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/post_create.html'
    if request.method == 'POST':
        form = PostForm(
            request.POST,
            files=request.FILES or None
        )
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()
            return redirect('posts:profile', request.user)
        else:
            return render(request, template, {'form': form})
    else:
        form = PostForm()
    return render(request, template, {'form': form})


@login_required
def post_edit(request, post_id):
    template = 'posts/post_create.html'
    is_edit = True
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    context = {'form': form, 'is_edit': is_edit}
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    else:
        if form.is_valid():
            form.save()
            return redirect('posts:post_detail', post_id)
        else:
            return render(request, template, context)


@login_required
def post_delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    else:
        post.delete()
        return render(request, 'posts/post_delete.html')


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    template = 'posts/follow.html'
    post_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    following = Follow.objects.filter(
        author=author,
        user=request.user,
    ).exists()
    if request.user != author and following is False:
        follow = Follow.objects.create(
            author=author,
            user=request.user,
        )
        follow.save()
        return redirect('posts:index')
    else:
        return redirect('posts:profile', request.user)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    follow = Follow.objects.filter(
        author=author,
        user=request.user,
    )
    follow.delete()
    return redirect('posts:index')

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Последние обновления подписок
{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' %}
  {% comment %} {% load cache %}
  {% cache 20 index_page with page_obj %} {% endcomment %}
  <div class="container">
    <h1>Последние обновления подписок</h1>
    {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text|linebreaksbr }}</p>  
      {% if post.group %}   
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
      <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a> 
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
    </div>
  {% comment %} {% endcache %} {% endcomment %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Записи сообщества{{ group.title }}
{% endblock %} 
  {% block content %}
  <div class="container">
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>
    {% for post in page_obj %}
      <ul>
       <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text|linebreaksbr }}</p>    
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>  
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Последние обновления на сайте
{% endblock %}
{% block content %}
  {% if user.is_authenticated %}
    {% include 'posts/includes/switcher.html' %}
  {% endif %}
  {% load cache %}
  {% cache 20 index_page with page_obj %}
  <div class="container">
    <h1>Последние обновления на сайте</h1>
    {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text|linebreaksbr }}</p>  
      {% if post.group %}   
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
      <a href="{% url 'posts:post_detail' post.id %}">подробная информация</a> 
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
    </div>
  {% endcache %}
{% endblock %}

yatube/templates/posts/post_create.html
{% extends "base.html" %}
{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %} 
{% endblock %}
{% block content %}
{% load user_filters %}
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if is_edit %}
                  Редактировать пост
                {% else %}
                  Новый пост
                {% endif %}            
              </div>
              <div class="card-body">
                {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endif %}
                {% if is_edit %}       
                  <form method="post" enctype="multipart/form-data">
                {% else %}
                  <form method="post" enctype="multipart/form-data"
                  action="{% url 'posts:post_create' %}">
                {% endif %}
                  {% load user_filters %}
                  {% csrf_token %} 
                  {% for field in form %}          
                    <div class="form-group row my-3 p-3">
                      <label for="{{ field.id_for_label }}">
                        {{ field.label }}
                          {% if field.field.required %}                  
                            <span class="required text-danger" >*</span>
                          {% endif %}                  
                      </label>
                      {{ field|addclass:'form-control' }}
                        {% if field.help_text %}              
                          <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                            {{ field.help_text|safe }}
                          </small>
                        {% endif %}                  
                    </div>
                    {% endfor %}            
                    <div class="d-flex justify-content-end">
                      <button type="submit" class="btn btn-primary">
                        {% if is_edit %}
                          Сохранить
                        {% else %}
                          Добавить
                        {% endif %} 
                      </button>
                    </div>
                  </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock %}

yatube/templates/posts/post_delete.html
{% extends 'base.html' %}
{% block title %}Удаление поста{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Удаление поста
      </div>
      <div class="card-body">
        <p>
          Пост удален
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Пост {{ post.text|slice:':30' }}{% endblock %}
{% block content %}
{% load user_filters %}
  <main>
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }}  
          </li>
          <!-- если у поста есть группа -->
            {% if post.group %}   
            <li class="list-group-item">
              Группа: {{ group.title }}
              <a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы
              </a>
            {% endif %}   
            </li>
            <li class="list-group-item">
              Автор: {{ post.author }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{ post_count }}</span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author %}">
              все посты пользователя
            </a>
          {% if post.author.username == user.username %}  
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:post_edit' post.id %}">
              редактировать пост
            </a>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:post_delete' post.id %}">
              удалить пост
            </a>
          </li>
          {% endif %}
          {% if user.is_authenticated %}
            <div class="card my-4">
              <h5 class="card-header">Добавить комментарий:</h5>
              <div class="card-body">
                <form method="post" action="{% url 'posts:add_comment' post.id %}">
                  {% csrf_token %}      
                  <div class="form-group mb-2">
                    {{ form.text|addclass:"form-control" }}
                  </div>
                  <button type="submit" class="btn btn-primary">Отправить</button>
                </form>
              </div>
            </div>
          {% endif %}

          {% for comment in comments %}
            <div class="media mb-4">
              <div class="media-body">
                <h5 class="mt-0">
                  <a href="{% url 'posts:profile' comment.author.username %}">
                    {{ comment.author.username }}
                  </a>
                </h5>
                  <p>
                  {{ comment.text }}
                  </p>
                </div>
              </div>
          {% endfor %} 
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text|linebreaksbr }}
        </p>
      </article>
    </div> 
  </main>
  {% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Профайл пользователя {{ profile_user }}{% endblock %}
{% block content %}
  <main>
    <div class="container py-5">        
      <h1>Все посты пользователя {{ profile_user }} </h1>
      <h3>Всего постов: {{ post_count }} </h3>
    {% if user.is_authenticated %}
      {% if user != profile_user %}  
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' profile_user.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' profile_user.username %}" role="button"
            >
              Подписаться
            </a>
        {% endif %}
      {% endif %}
    {% endif %} 
      {% for post in page_obj %}
      <article>   
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }} 
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text|linebreaksbr }}
        </p>
        <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>     
      {% if post.group %}   
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %} 
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
         
      <hr>
      <!-- Остальные посты. после последнего нет черты -->
      <!-- Здесь подключён паджинатор -->  
    {% include 'posts/includes/paginator.html' %}     
    </div>
  </main>
{% endblock %}